[book]
authors = ["JUN JIE NAN"]
language = "zh_CN"
multilingual = false
src = "src"
title = "Thatched Cottage"

[preprocessor.fix-cjk-spacing]
[preprocessor.mermaid]


[output.html]
no-section-label = true
mathjax-support = true

[output.html.fold]
enable = true
level = 0
