#+LINK: netmapinetd https://github.com/nanjj/netmapinetd
#+LINK: atc12-final186.pdf https://www.usenix.org/system/files/conference/atc12/atc12-final186.pdf
#+LINK: rizzo https://www.usenix.org/conference/atc12/technical-sessions/presentation/rizzo
#+LINK: netmap-framework http://queue.acm.org/detail.cfm?id=2103536
#+LINK: netmap-tutorial https://github.com/vmaffione/netmap-tutorial
#+LINK: netmap-github https://github.com/luigirizzo/netmap
#+LINK: netmap-page http://info.iet.unipi.it/~luigi/netmap
#+LINK: netstack https://github.com/google/netstack
#+LINK: warpcore https://github.com/NTAP/warpcore
#+LINK: stack-receiving https://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/
#+LINK: pcap  http://yuba.stanford.edu/~casado/pcap/section1.html
#+LINK: epoll example https://banu.com/blog/2/how-to-use-epoll-a-complete-example-in-c
#+LINK: DummynetRevisited http://info.iet.unipi.it/~luigi/papers/20091201-dummynet.pdf
#+LINK: PfOnMacOSX https://pleiades.ucsc.edu/hyades/PF_on_Mac_OS_X
#+LINK: Jekyll https://jekyllrb.com/
#+LINK: Hugo https://gohugo.io/
#+LINK: Google http://www.google.com/search?q=%s
#+LINK: nmap https://nmap.org/
#+LINK: ncat guide https://nmap.org/ncat/guide/index.html
#+LINK: ncat https://nmap.org/ncat/
- [2019.01.03] [[file:lxd.org][LXD]]

	LXD setup, usage and more.
- [2017.12.20] [[file:tips.org][Tips]]

	Some tips about linux kernel, ssh, qemu, ncat and more.
- [2017.12.06] [[file:arista.org][Running Arista vEOS in OpenStack]]

	How to run arista vEOS in OpenStack.
- [2017.10.27] [[file:freebsd-cloud.org][FreeBSD Cloud]]

	How to setup cloudinit for freebsd and how to do disk resize under freebsd.
- [2018.07.27] [[file:godebug.org][Go Debug]]

	How to do go debug.
- [2017.12.25] [[file:kids.org][My Kids]]

	Some interesting words from my kids.
- [2017.10.24] [[file:org-publish.org][Publish Github Pages via Org Mode]]

	Now switched from [[Jekyll][Jekyll]], [[Hugo][Hugo]] to Emacs Org Publish. How to write blog using org-publish.
- [2017.10.26] [[file:dummynet.org][Dummynet Usage on Mac]]

	Here some =dummynet= usages on Mac
- [2019.12.07] [[file:gitlab-ci.org][Gitlab的持续集成]]

	Gitlab持续集成采用订阅模式，这和Github不同。
- [2017.11.07] [[file:netmap.org][Netmap]]

	[[netmap-page:][Netmap]] is a framework for very fast packet I/O from userspace.
- [2019.12.03] [[file:hdiutil.org][Manipulate Disk Images Under Mac]]

	How to manipulate disk images under macOS.
