#!/bin/bash
function link_post()
{
    post=$1
    name=$(basename $post)
    name=${name:11}
    ln -fs $post $name
}

link=$1
cd $(dirname $0)/_pages
if [ "$link" = "-l" -o "$link" = "--link" ]; then
    rm *.md
    for file in ../_posts/*.md; do
        link_post $file
    done
    exit 0
fi

title=$1
category=$2
post="../_posts/$(date +%F)-$(echo ${title}|tr '[A-Z ]' '[a-z-]').md"
cat > ${post} <<EOF
---
layout: page
title: "${title}"
category: ${category}
date: $(date +'%F %T')
---

\`\`\`
$(figlet "${title}")
\`\`\`

---
1. TOC
{:toc}
---
EOF

link_post $post
