[tasks.all]
dependencies = ["release"]

[tasks.release]
script = [
	   "rm book/*.rs",
	   "cp -rf book/* ."
]
dependencies = ["build"]

[tasks.build]
command = "mdbook"
args = ["build"]
dependencies = ["clean"]

[tasks.clean]
command = "mdbook"
args = ["clean"]
