[tasks.install]
command="cargo"
args = ["install", "--path", "."]

[tasks.build]
dependencies = ["bookcopy"]

[tasks.bookcopy]
script = [
	   "rm -rf book/*.rs",
	   "cp -rf book/* ."
]
dependencies = ["bookbuild"]

[tasks.publishall]
script = [
	   "(cd book; tar cvfz ../site.tar.gz .)",
	   "~/bin/publish"
]

[tasks.bookbuild]
command = "mdbook"
args = ["build"]
dependencies = ["bookclean"]

[tasks.bookclean]
command = "mdbook"
args = ["clean"]
