[tasks.install]
command="cargo"
args = ["install", "--path", "."]

[tasks.build]
dependencies = ["bookcopy"]

[tasks.bookcopy]
script = [
	   "rm -rf book/*.rs",
	   "cp -rf book/* ."
]
dependencies = ["bookbuild"]

[tasks.all]
script = [
	   "(cd book; tar cfz ../site.tar.gz .)",
	   "time acurl -Fcontent=@site.tar.gz https://pages.sr.ht/publish/nanjj.srht.site"
]
[tasks.some]
script = [
	   "./some.sh"
]
[tasks.bookbuild]
command = "mdbook"
args = ["build"]
dependencies = ["bookclean"]

[tasks.bookclean]
command = "mdbook"
args = ["clean"]
