[tasks.install]
command="cargo"
args = ["install", "--path", "."]

[tasks.build]
dependencies = ["bookcopy"]

[tasks.bookcopy]
script = [
	   "rm -rf book/*.rs",
	   "cp -rf book/* ."
]
dependencies = ["bookbuild"]

[tasks.bookbuild]
command = "mdbook"
args = ["build"]
dependencies = ["install", "bookclean"]

[tasks.bookclean]
command = "mdbook"
args = ["clean"]
